### ISSUE TITLE
Keep manifesto principles in consistent form? 

### ISSUE THREAD

**Issue by opendigitalsafety** [codeisscience/manifesto#22]
I really enjoyed reading this manifesto, and it made me think of a similar call to action I've sometimes heard data scientists make about data.

One thing that sticks out to me, though, about your manifesto is that I think it would be easier to remember the principles if they were all in the same grammatical form. For example, you sometimes have a fragment of a sentence, like "Open over Closed" or "Code for the Future." Other times, you have complete sentences--"Incorrect code results in incorrect science." Maybe make every principle a sentence? Or every principle a fragment? 

This is another little thing, but looking at other manifestos, I see that "X over Y" is a convention that's used often, so it might be interesting to depart from that and try something different. I don't think you have say that something is important--or necessary--by having it eclipse something else.

**Comment by yochannah** [comment]
I'm pretty happy with how the wording is at the moment, but I'd also be happy to consider any specific PRs / suggestions to reword if you have any :)

**Comment by yochannah** [comment]
we'll be freezing the text and launching the manifesto soon - closing this issue
