### ISSUE TITLE
Add "tweet this" button to index.md

### ISSUE THREAD

**Issue by yochannah** [codeisscience/manifesto#23]
Inspired by https://twitter.com/jjmerelo/status/994605979953254405 - can we add a "tweet this" button with similar text to what @JJ used? 

The file to edit: https://github.com/codeisscience/manifesto/blob/master/index.md 

You can use this site to generate the button: https://publish.twitter.com/?buttonType=TweetButton&widget=Button 

## if you want to pick up this task

1. Comment on this issue stating that you intend to work on the task
2. When you're ready, add your work to the repo and create a pull request.
3. Bask in glory and email me your address if you'd like to have some codeisscience stickers for your trouble. <3

### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), pop by to say hi on [gitter](https://gitter.im/codeisscience/Lobby) or if needed email yochannah@gmail.com <3

**Comment by Ilozuluchris** [comment]
Hi, I wish to work on this

**Comment by yochannah** [comment]
Awesome, feel free to get started! I'm travelling to the sprint site in
london for the next hour or so but I'll do my best to answer any questions.

**Comment by JJ** [comment]
Maybe something like this:

```
<a href="https://twitter.com/intent/tweet?button_hashtag=codeiscience&ref_src=twsrc%5Etfw" class="twitter-hashtag-button" data-size="large" data-text="I adhere to the #codeiscience manifesto" data-url="https://codeisscience.github.io/manifesto/" data-related="codeiscience" data-show-count="false">Tweet #codeiscience</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
```
