### ISSUE TITLE
manifesto seems inconsistent

### ISSUE THREAD

**Issue by egonw** [codeisscience/manifesto#26]
At the start the manifesto writes:

```
... [scientific code] needs to be treated as a primary research output
```

But later it writes:

```
Code published in journals should be peer reviewed.
```

While the second quote does not specifically demote it, any code should be peer reviewed, also if not published in journals. After all, if it only applies to code with a journal article, then the scientific code is **secondary** research output, not primary.

**Comment by yochannah** [comment]
fixed by #27
