### ISSUE TITLE
Suggestion: use 80 character width for lines?

### ISSUE THREAD

**Issue by drvinceknight** [codeisscience/manifesto#29]
Currently there is no line width on `manifesto.md` which makes the diffs slightly harder to read. For example: https://github.com/codeisscience/manifesto/pull/28/files looks like a long diff but is just a single word added to the sentence.

If it's helpful to put in a max width (the markdown still renders fine): I'm happy to PR this.

**Comment by yochannah** [comment]
sure, go ahead! And thanks!

**Comment by drvinceknight** [comment]
Done: https://github.com/codeisscience/manifesto/pull/30 :+1:

And thank you for putting this together and maintaining it :+1: :heart:
