### ISSUE TITLE
We need your help to create a poster!!!

### ISSUE THREAD

**Issue by yochannah** [codeisscience/manifesto#32]
Hey cool people! We've had the manifesto accepted for a talk / poster for GCCBOSC. This is fabulous! So now it's time to actually *make* the poster. 

## Specs

**Size:** A0 - 118.9 x 84.1cm

**Poster contents:**

- Header
    - Logo - use model 1 or 2: https://github.com/yochannah/code-is-science/tree/master/static/images
    - Title: "Code is Science - a manifesto for anyone who deals with code in a scientific scenario"
    - Authors and academic affiliations: Yo Yehudi, University of Cambridge, Alexander Konovalov [affiliation to follow], Selina Aragon [affiliation to follow] - @selina-aragon @alex-konovalov can you update with your details when you get a chance? 
- Main body: 
    - the preamble and text for each of the five manifesto concepts, as worded here: https://codeisscience.github.io/manifesto/manifesto (note - there's no need to includethe background or footer from the manifesto webpage)
    - the fantastic icons designed by Yee Mun beside each of the five manifesto concepts: https://github.com/codeisscience/manifesto/tree/master/codeisscience 
- Footer
    - Credits to yourself for the poster design, as well as Yee Mun @yeemunnn for the icon design. 
    - link to codeisscience.com 

Here's some good academic poster guidance: https://colinpurrington.com/tips/poster-design

**Output formats**
- original editor format (this will depend on whatever editor you end up choosing) 
- PDF 
- SVG.

**graphics editor** I'd recommend using a vector editor such as [Inkscape](https://inkscape.org/en/) or [Gravit Designer](https://www.designer.io/) - they're both free, but Inkscape is open source. Gravit isn't open, but is somewhat easier to use.

### It's due soon! 
I'll be leaving for GCCBOSC on the 23rd of June, so ideally we need to wrap up the poster no later than the 12th of June to give us time to order the poster and for it to arrive. I'll pick this up on the 12th if no one else has had a chance to look at it. 

## if you want to pick up this task

1. Comment on this issue stating that you intend to work on the task
2. When you're ready, add your work to the repo and create a pull request.
3. Bask in glory and email me your address if you'd like to have some codeisscience stickers (plus perhaps some fliers of this poster!) for your trouble. <3

### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), pop by to say hi on [gitter](https://gitter.im/codeisscience/Lobby) or if needed email yochannah@gmail.com <3

**Comment by yochannah** [comment]
I have a draft - does anyone have time to proofread it for me? https://github.com/yochannah/manifesto/blob/poster/poster/poster.pdf

**Comment by drvinceknight** [comment]
I'm just going out to do the groceries but I'll take a look when I get back! (30 mins or so)

**Comment by drvinceknight** [comment]
@yochannah some comments that correspond to the text of `manifesto.md` (because I'm reading the poster carefully, so apologies about this and please ignore if unhelpful). These could well just require me to update my english language version :)

> Through working with scientific code,...

This sounded weird to me. Perhaps it's how "manifestos" are generally written. I would suggest:

"We agree that scientific code needs to be treated as a primary research output"

> Historically, science has been reviewed by its peers

Does science (as a subject) have peers? I would suggest:

"Historically, the work of scientists has been reviewed by their peers"

>  It is important recognise that people 

"It is important to recognise that people

I haven't found any typos etc in the poster itself: it's a true replication of `manifesto.md` and looks great! :+1: :+1:

**Comment by yochannah** [comment]
@drvinceknight thanks for the review! Especially that last one - I guess I automatically added the "to" in as brains are wont to do. Does #36 look right to you?

**Comment by yochannah** [comment]
Poster is printed!
