### ISSUE TITLE
Add .cff file to repo (citation guidelines)

### ISSUE THREAD

**Issue by yochannah** [codeisscience/manifesto#35]
See details [here]( https://citation-file-format.github.io/) for .cff standards and see #25 and #32 for guidelines on who should be credited as authors.

## if you want to pick up this task

1. Comment on this issue stating that you intend to work on the task
2. When you're ready, add your work to the repo and create a pull request.
3. Bask in glory and email me your address if you'd like to have some codeisscience stickers for your trouble. <3

### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), pop by to say hi on [gitter](https://gitter.im/codeisscience/Lobby) or if needed email yochannah@gmail.com <3

**Comment by yochannah** [comment]
The text for the manifesto is officially frozen - I have 5,000 leaflets in my living room that read it so no changes are allowed ;)

**Comment by JPTIZ** [comment]
Ok, I think I can do this on this Sunday, October 27th :) Should I assign myself then?

**Comment by yochannah** [comment]
Yes! 😍😍

**Comment by alex-konovalov** [comment]
@yochannah I've distributed leaflets that you have sent me earlier, can help with the next batch!
