### ISSUE TITLE
404

### ISSUE THREAD

**Issue by da5nsy** [codeisscience/manifesto#40]
`https://www.codeisscience.com` and `https://www.codeisscience.github.io/` are currently 404ing (but `https://codeisscience.github.io/manifesto/` appears fine?)

**Comment by yochannah** [comment]
We moved the repo (from my personal account to the org account) and it looks like some settings broke. I've updated the DNS settings - it isn't fixed for me yet but I'll try again in 24 hours.

**Comment by yochannah** [comment]
hmm, re-configured as my last fix still didn't do it - will check again in 24h 😆

**Comment by yochannah** [comment]
needed some additional config tweaks, but now fixed!
